baseURL = "https://www.cloudytuts.com/"
languageCode = "en-us"
title = "CloudyTuts"
theme = "cloudytuts"
googleAnalytics = "UA-39527242-4"

defaultContentLanguage = "en"
enableRobotsTXT = true
disableBrowserError = true

paginate = 9

contentDir = "content/en"

staticDir = "static"

timeout = 3000

enableGitInfo = true

sectionPagesMenu = "main"

[permalinks]
tutorials = "/:sections/:title"
blog = "/:year/:month/:day/:title"
topics = "/:sections/:title"
news = "/news/:year/:month/:day/:title"

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

# Be explicit about the output formats. We (currently) only want an RSS feed for the home page.
[outputs]
#home = [ "HTML", "RSS", "HEADERS" ]
home = [ "HTML", "RSS" ]
page = [ "HTML"]
section = [ "HTML"]

[params]
mainSections = ["blog","tutorials","guides","news"]
header = "News, Guides, and Tutorials for the Cloud"
twitter = "cloudytuts"
facebook = "cloudytuts"
github = "cloudytuts" 
logo = "https://www.cloudytuts.com/images/cloudytuts-social.jpg"

[minify]
  disableJSON = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepDocumentTags = true
      keepQuotes = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  author = "author"
  contributor = "contributors"

[related]
  threshold = 1
  includeNewer = true
  toLower = false

  [[related.indices]]
    name = "series"
    weight = 100

  [[related.indices]]
    name = "tags"
    weight = 65

  [[related.indices]]
    name = "categories"
    weight = 50

  [[related.indices]]
    name = "author"
    weight = 50

  [[related.indices]]
    name = "section"
    weight = 25

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

githubbranch = "master"
docsbranch = "master"
githubWebsiteRepo = "github.com/serainville/cloudytuts.com"
githubWebsiteRaw = "raw.githubusercontent.com/serainville/cloudytuts.com"