[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

    [plugins.inputs]
    baseUrl = "https://www.cloudytuts.com"
    sitemapPath "/sitemap.xml"
    providers = [
        "google",
        "bing",
        "yandex"
    ]
